### ISSUE TITLE
OpenApi Rules

### ISSUE THREAD

**Issue by dkoeni** [swissfintechinnovations/.github#18]
Please comment for new proposals of SFTI's naming conventions concerning the openAPI action / redocly workflow

**Comment by dkoeni** [comment]
body request and response parameters in snake_case according to ISO 23029

**Comment by dkoeni** [comment]
summary must not end with an fullstop

**Comment by dkoeni** [comment]
naming conventions for tags

**Comment by dkoeni** [comment]
Use refs for parameters or schemas used multiple times

**Comment by andiahlm** [comment]
Adjust ordering of root objects to redocly conventions.

openapi:
info:
servers:
security:
tags:
externalDocs:
paths:

Reasoning:

We use 'redocly bundle' command to build complete OAS. Redocly reorders root object according to their conventions:

**Comment by andiahlm** [comment]
Adapt naming-conventions for parameters to OAS common practices

Most used practice is camelCase with 'Param'-Suffix:

```yaml
parameters:
  skipParam:
    name: skip
    in: query
    description: number of items to skip
    required: true
    schema:
      type: integer
      format: int32
  limitParam:
    name: limit
    in: query
    description: max records to return
    required: true
    schema:
      type: integer
      format: int32
```
